### ISSUE TITLE
Getting profession, game piece and playing order

### ISSUE THREAD

**Issue by swapnillothe** [STEP-tw/cashflow-punters#23]
As a player
     I want to know the profession, game piece and 
     playing order 
     So that I will aware of game setup

Acceptance Criteria -

- [ ] Given the game has started 
when I'm looking at screen
then I should be able to see everyones - 
- [ ] profession
- [ ] game piece
- [ ]  playing turn

**Comment by sapanaKale** [comment]
This issue is combined with another one
